spring:
  application:
    name: agro-inteligente
  profiles:
    active: dev
  jackson:
    time-zone: America/Bogota
    serialization:
      write-dates-as-timestamps: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    root: INFO
    com.agrointeligente: DEBUG
