spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agro_inteligente
    username: agro_user
    password: agro_password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
