spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/agrointeligente}
    username: ${DATABASE_USERNAME:agrointeligente}
    password: ${DATABASE_PASSWORD:agrointeligente}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    show-sql: false

