@startuml nivel 1 gestionar usuarios
left to right direction

skinparam actorStyle awesome
actor "Administrador" as Admin

package "Gestionar Usuarios" {

  usecase "Crear Cuenta\nde Usuario" as UC1
  usecase "Editar Datos\nde Usuario" as UC2
  usecase "Listar Usuarios\nRegistrados" as UC3
  usecase "Desactivar Cuenta\nde Usuario" as UC4
  usecase "Reactivar Cuenta\nde Usuario" as UC5
  usecase "Asignar Rol\ny Permisos" as UC6
  usecase "Enviar Contraseña\nTemporal" as UC7
  usecase "Validar Datos\ndel Usuario" as UC8
  usecase "Cambiar Rol\ndel Usuario" as UC9
  usecase "Buscar Usuario" as UC10
  usecase "Consultar Actividad\ndel Usuario" as UC11
  usecase "Confirmar\nDesactivación" as UC12
}

Admin --> UC1
Admin --> UC2
Admin --> UC3
Admin --> UC4
Admin --> UC5

UC1 ..> UC6 : <<include>>
UC1 ..> UC7 : <<include>>
UC1 ..> UC8 : <<include>>

UC2 ..> UC8 : <<include>>
UC2 ..> UC9 : <<extend>>

UC3 ..> UC10 : <<extend>>
UC3 ..> UC11 : <<extend>>

UC4 ..> UC12 : <<include>>

@enduml