@startuml nivel 1 gestionar insumos agricolas
left to right direction

skinparam actorStyle awesome
actor "Productor Agrícola" as Productor

package "Gestionar Insumos Agrícolas" {

  usecase "Registrar Aplicación\nde Insumo" as UC1
  usecase "Editar Registro\nde Insumo" as UC2
  usecase "Listar Insumos\nde un Cultivo" as UC3
  usecase "Eliminar Registro\nde Insumo" as UC4
  usecase "Gestionar Catálogo\nde Insumos" as UC5
  usecase "Consultar Catálogo\nde Insumos" as UC6
  usecase "Seleccionar Cultivo\nDestino" as UC7
  usecase "Validar Datos\ndel Insumo" as UC8
  usecase "Alertar por Insumo\nde Alto Impacto" as UC9
  usecase "Calcular Costo Total\nde Insumos" as UC10
  usecase "Confirmar Eliminación" as UC11
}

Productor --> UC1
Productor --> UC2
Productor --> UC3
Productor --> UC4
Productor --> UC5

UC1 ..> UC6 : <<include>>
UC1 ..> UC7 : <<include>>
UC1 ..> UC8 : <<include>>
UC1 ..> UC9 : <<extend>>

UC3 ..> UC10 : <<extend>>

UC4 ..> UC11 : <<include>>

@enduml